name: APK Build and Upload

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        default: 'develop'
        required: true

jobs:
  build:
    runs-on: github-runner-dune
    env:
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Decode and place keystore
        if: env.KEYSTORE_BASE64 != ''
        run: |
          mkdir -p sign
          echo "${{ env.KEYSTORE_BASE64 }}" | base64 --decode > sign/keystore.jks

      - name: Run lint check
        run: ./gradlew lint

      - name: Run unit tests
        run: ./gradlew testDevDebugUnitTest

      - name: Build DEMO debug APK
        run: ./gradlew assembleDemoDebug

      - name: Upload DEMO debug APK
        uses: actions/upload-artifact@v4
        with:
          name: demo-debug-apk
          path: app/build/outputs/apk/demo/debug/*.apk
          retention-days: 90

      - name: Build DEMO release APK
        run: ./gradlew assembleDemoRelease

      - name: Upload DEMO release APK
        uses: actions/upload-artifact@v4
        with:
          name: demo-release-apk
          path: app/build/outputs/apk/demo/release/*.apk
          retention-days: 90