name: PR checks

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'AV Android Wallet'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7

      - name: Upload OWASP Dependency-Check results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-results
          path: '**/dependency-check-report.*'
          retention-days: 20

  lint-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        cache-read-only: false

    - name: Run lint check
      run: ./gradlew lint

    - name: Run unit tests
      run: ./gradlew testDevDebugUnitTest

    - name: Run tests with coverage
      run: ./gradlew koverHtmlReportDevDebug

    - name: Upload test results only on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/reports/kover
        retention-days: 20

    - name: Build DEV debug APK
      run: ./gradlew assembleDevDebug