name: Android Unit Tests and Debug Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'AV Android Wallet'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7

      - name: Upload OWASP Dependency-Check results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-results
          path: '**/dependency-check-report.*'

  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        cache-read-only: false

    - name: Run lint check
      run: ./gradlew lint

#    - name: Run Detekt - configure it for Compose?
#      run: ./gradlew detekt

    - name: Run unit tests
      run: ./gradlew testDevDebugUnitTest

    - name: Run tests with coverage
      run: ./gradlew koverHtmlReportDevDebug

    - name: Upload test results only on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          **/build/reports/tests/
          **/build/reports/kover

    - name: Build DEV debug APK
      run: ./gradlew assembleDevDebug

    # - name: Upload debug APK
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: debug-apk
    #     path: app/build/outputs/apk/debug/*.apk